import { units, categories, available, money, itemPrice, subtotal, orderStates } from './data.js';
import { state, catalog, discount } from './store.js';
export const escape = value => String(value ?? '').replace(/[&<>"']/g, character => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[character]));
export const button = (text, action, extra = '', style = '') => `<button class="button ${style}" data-action="${action}" ${extra}>${text}</button>`;
export const head = (title, text) => `<div class="page-head"><h1>${title}</h1><p>${text}</p></div>`;
export function productsView() {
  const selection = catalog().filter(product => (state.category === 'Tudo' || product.category === state.category) && `${product.name} ${product.description}`.toLocaleLowerCase('pt-BR').includes(state.search.toLocaleLowerCase('pt-BR')));
  if (!selection.length) return '<div class="empty" role="status"><h3>Nenhum produto encontrado</h3><p>Tente outro nome ou escolha uma categoria diferente.</p></div>';
  return selection.map(product => `<article class="product"><img class="product-image" src="assets/${product.image}.svg" alt="Ilustração de ${escape(product.name)}" width="300" height="200" loading="lazy"><div class="product-content">${product.tag ? `<span class="tag">${product.tag}</span>` : ''}${!available(product, state.unit) ? `<span class="tag unavailable">${product.seasonal !== undefined ? 'Fora da temporada' : 'Esgotado'}</span>` : ''}<h3>${product.name}</h3><p>${product.description}</p><div class="product-bottom"><span class="product-price">${money(product.price)}</span><button class="add-button" data-action="product" data-id="${product.id}" ${!available(product, state.unit) ? 'disabled' : ''} aria-label="Escolher ${product.name}">Escolher +</button></div></div></article>`).join('');
}
export function cartView(checkout = true) {
  return `<h2>Sua sacola</h2>${state.cart.length ? state.cart.map((item, index) => `<div class="cart-line"><div><strong>${escape(item.name)}</strong>${item.extras.length ? `<small>+ ${item.extras.map(extra => escape(extra.name)).join(', ')}</small>` : ''}${item.note ? `<small>Obs.: ${escape(item.note)}</small>` : ''}<div class="quantity"><button data-action="quantity" data-index="${index}" data-delta="-1" aria-label="Diminuir ${escape(item.name)}">−</button><span>${item.quantity}</span><button data-action="quantity" data-index="${index}" data-delta="1" aria-label="Aumentar ${escape(item.name)}">+</button></div></div><strong>${money(itemPrice(item) * item.quantity)}</strong></div>`).join('') : '<div class="cart-empty"><span aria-hidden="true">♧</span><strong>Ainda cabe um sabor da nossa terra.</strong><p>Escolha seu primeiro item no cardápio.</p></div>'}<div class="totals"><span>Subtotal</span><strong>${money(subtotal(state.cart))}</strong></div>${checkout ? button('Revisar pedido →', 'checkout', state.cart.length ? '' : 'disabled', 'full') : ''}<p class="hint">Retirada em ${units.find(unit => unit.id === state.unit).name}. Sem taxa de entrega.</p>`;
}
export function menuView() {
  const unit = units.find(unit => unit.id === state.unit);
  return `<section class="hero"><div class="hero-copy"><p class="eyebrow">Feito aqui. Com gosto de casa.</p><h1>Um pedacinho do Nordeste<br>na sua próxima pausa.</h1><p>Do cuscuz quentinho ao café passado: escolha o seu favorito e retire na nossa unidade.</p><span class="pill">Retirada em ${unit.time} · ${unit.format}</span></div><img class="hero-art" src="assets/mesa.svg" alt="Ilustração de uma mesa com cuscuz, café e tapioca" width="600" height="350"></section>${state.channel === 'totem' ? '<p class="channel-note">Autoatendimento: faça seu pedido sem cadastro. A sessão é encerrada após 2 minutos sem interação.</p>' : state.channel === 'app' ? '<p class="channel-note">Modo App: pedidos antecipados e fidelidade na mesma jornada. Representação web do aplicativo.</p>' : ''}<div class="menu-layout"><section aria-label="Cardápio"><div class="menu-top"><div class="section-heading"><div><h2>Cardápio da unidade</h2><small>${unit.name}</small></div></div><label class="search"><span class="sr-only">Buscar no cardápio</span><input id="search" type="search" placeholder="O que você quer comer?" value="${escape(state.search)}"></label></div><div class="category-bar" aria-label="Categorias">${categories.map(category => `<button class="chip ${category === state.category ? 'active' : ''}" data-action="category" data-category="${category}" aria-pressed="${category === state.category}">${category}</button>`).join('')}</div><div class="products" id="products">${productsView()}</div><p class="hint">Combo Pausa nordestina: preço promocional de ${money(1790)}. Não acumula com outro cupom. Cardápio, valores e disponibilidade são fictícios.</p></section><aside class="cart-summary" id="cart" aria-label="Resumo do pedido">${cartView()}</aside></div>`;
}
export function checkoutView() {
  if (!state.cart.length) return head('Sua sacola está vazia', 'Volte ao cardápio e escolha um produto.') + button('Ver cardápio', 'menu');
  const unit = units.find(unit => unit.id === state.unit);
  return `${head('Só falta confirmar.', 'Confira os itens, a unidade e o pagamento. O pedido é para retirada no balcão.')}<div class="grid-two"><div><section class="card"><h2>Retirada</h2><p><strong>${unit.name}</strong><br>${unit.address}<br>Previsão após confirmação: ${unit.time}</p><p class="hint">Não há entrega a domicílio nesta proposta.</p></section><section class="card" style="margin-top:1rem"><h2>Pagamento externo</h2><div class="info">Simulação do envio e retorno de um serviço de pagamento. Não informe cartão, CPF ou dados bancários.</div><form class="form" id="payment-form"><label>Forma de pagamento<select name="method"><option value="pix">Pix</option><option value="cartao">Cartão em ambiente externo</option></select></label><label>Resultado da simulação<select name="result"><option value="aprovado">Aprovado</option><option value="recusado">Recusado</option><option value="pendente">Sem retorno / pendente</option></select></label><label class="check"><input type="checkbox" name="terms" required>Li o aviso sobre os dados do pedido e a <a href="#privacidade">privacidade</a>.</label><button class="button full" type="submit">Solicitar pagamento simulado · ${money(subtotal(state.cart) - discount())}</button></form></section></div><aside class="card">${cartView(false)}<div class="info">${state.user ? `Olá, ${escape(state.user.name)}. Você tem ${state.user.points} pontos.` : 'Você pode pedir sem cadastro. Entre na conta se quiser acumular pontos.'}</div>${state.user?.points >= 100 ? `<label class="check"><input type="checkbox" id="redeem" ${state.redeem ? 'checked' : ''}> Usar 100 pontos para até R$ 5,00 de desconto</label>` : ''}<div class="totals"><span>Benefício</span><strong>− ${money(discount())}</strong></div><div class="totals"><span>Total</span><strong>${money(subtotal(state.cart) - discount())}</strong></div>${button('Voltar ao cardápio', 'menu', '', 'secondary full')}<p class="hint">Pontos e desconto só são efetivados com pagamento aprovado.</p></aside></div>`;
}
export function ordersView() {
  return head('Cada etapa, bem pertinho.', 'Acompanhe a confirmação, o preparo e a retirada. O código abaixo identifica seu pedido no balcão.') + (!state.orders.length ? `<div class="empty"><h2>Nenhum pedido por enquanto</h2><p>Seus pedidos desta sessão aparecem aqui.</p>${button('Escolher meu pedido', 'menu')}</div>` : state.orders.map(order => `<section class="card order"><div class="order-head"><span class="order-code">${order.code}</span><span class="status ${order.payment !== 'aprovado' ? 'pending' : ''}">${order.payment === 'aprovado' ? orderStates[order.stage] : `Pagamento ${order.payment}`}</span></div><p class="hint">${units.find(unit => unit.id === order.unit).name} · ${order.channel.toUpperCase()} · ${money(order.total)}</p>${order.items.map(item => `<p>${item.quantity} × ${escape(item.name)}${item.extras.length ? ' + ' + item.extras.map(extra => escape(extra.name)).join(', ') : ''}</p>`).join('')}${order.payment === 'aprovado' ? `<ol class="timeline">${orderStates.map((step, index) => `<li class="${index <= order.stage ? 'done' : ''}" ${index === order.stage ? 'aria-current="step"' : ''}>${index + 1}. ${step}</li>`).join('')}</ol><p class="hint">${order.credited ? `${order.points} pontos creditados uma única vez. ${order.discount ? '100 pontos utilizados no benefício.' : ''}` : 'Pedido sem programa de fidelidade.'}</p>${order.stage === 2 ? '<div class="info success">Seu pedido está pronto. Informe o código no balcão.</div>' : ''}` : order.payment !== 'cancelado' ? `<div class="${order.payment === 'recusado' ? 'error' : 'info'}">${order.payment === 'recusado' ? 'Pagamento não aprovado. Revise o meio de pagamento antes de tentar novamente.' : 'Ainda não recebemos confirmação. O pedido não foi enviado à cozinha. Consulte o resultado antes de refazer.'}</div><div class="actions">${button('Simular confirmação', 'retry', `data-id="${order.id}"`)}${button('Encerrar tentativa', 'abandon', `data-id="${order.id}"`, 'secondary')}</div>` : '<p class="hint">Tentativa encerrada sem cobrança. Faça um novo pedido no cardápio.</p>'}</section>`).join(''));
}
export function loyaltyView() {
  return `${head('Toda visita deixa raízes.', 'A cada R$ 1,00 pago, você ganha 1 ponto. O saldo desta demonstração existe somente na sessão atual.')}<div class="grid-two"><section class="card"><h2>Seus pontos</h2><p class="points">${state.user?.points || 0}<small style="font:1rem Arial"> pontos</small></p><p>${state.user ? `Conta de ${escape(state.user.name)}.` : 'Entre ou crie uma conta para participar. Pedir como visitante continua disponível.'}</p>${button(state.user ? 'Pedir e acumular' : 'Entrar na conta', state.user ? 'menu' : 'account')}</section><section class="card"><h2>Benefício da casa</h2><p><strong>100 pontos = até R$ 5,00 de desconto</strong></p><p>Ative o benefício na revisão do pedido. Se o pagamento for recusado, os pontos não são descontados.</p><p class="hint">Regra proposta para o projeto. Pontos não equivalem a dinheiro e não podem ser transferidos.</p></section></div><section class="info"><strong>Promoção disponível:</strong> o combo Pausa nordestina reúne tapioca de queijo e café por R$ 17,90. Campanhas personalizadas dependem de autorização separada em Privacidade.</section>`;
}
export function accountView() {
  if (state.user) return `${head('Sua conta', 'Seus dados fictícios ficam apenas na memória desta sessão.')}<section class="card"><h2>${escape(state.user.name)}</h2><p>${escape(state.user.email)}</p><p>${state.user.points} pontos no programa de fidelidade.</p><div class="actions">${button('Sair da conta', 'logout', '', 'secondary')}${button('Gerenciar privacidade', 'privacy')}</div></section>`;
  return `${head('Um cadastro, mais benefícios.', 'Acesso demonstrativo: use dados fictícios. Cadastro e login não se conectam a um servidor.')}<div class="grid-two"><section class="card"><h2>Entrar</h2><div class="info">Conta de teste: <strong>cliente@exemplo.com</strong><br>Senha: <strong>nordeste123</strong><br>Saldo inicial de teste: 100 pontos.</div><form class="form" id="login-form"><label>E-mail<input name="email" type="email" autocomplete="off" required maxlength="120"></label><label>Senha<input name="password" type="password" autocomplete="off" required minlength="8" maxlength="80"></label><button class="button" type="submit">Entrar na demonstração</button></form><div id="login-error" role="alert"></div></section><section class="card"><h2>Criar conta de teste</h2><form class="form" id="register-form"><label>Nome fictício<input name="name" autocomplete="off" required minlength="2" maxlength="60"></label><label>E-mail fictício<input name="email" type="email" autocomplete="off" required maxlength="120"></label><label>Senha de teste (mínimo 8 caracteres)<input name="password" type="password" autocomplete="off" required minlength="8" maxlength="80"></label><label class="check"><input name="loyalty" type="checkbox" required>Quero participar da fidelidade e li o aviso de dados.</label><label class="check"><input name="marketing" type="checkbox">Quero receber campanhas (opcional).</label><button class="button" type="submit">Criar conta de teste</button></form><div id="register-error" role="alert"></div></section></div>`;
}
export function privacyView() {
  return `${head('Seus dados. Suas escolhas.', 'Transparência para pedir, participar da fidelidade e escolher como receber novidades.')}<div class="grid-two"><section class="card"><h2>O que esta interface utiliza</h2><ul class="privacy-list"><li><strong>Pedido:</strong> produtos, unidade, canal, valor, observações e status para organizar a retirada.</li><li><strong>Conta:</strong> nome e e-mail fictícios para representar identificação e fidelidade.</li><li><strong>Preferências:</strong> autorizações opcionais, sem caixas pré-marcadas.</li><li><strong>Pagamento:</strong> somente meio e resultado simulado; não solicitamos dados de cartão.</li></ul><p class="hint">Os dados ficam na memória da página. Atualizar ou fechar a página reinicia a demonstração. Não há cookies de rastreamento, serviço analítico ou transmissão desses dados.</p><h3>Em uma implantação real</h3><p>Pedidos teriam finalidade contratual; marketing e segmentação precisariam de base legal definida e escolhas transparentes. Retenção, contato do controlador e atendimento dos direitos seriam formalizados antes da operação.</p><p class="hint">Esta interface ilustra controles de privacidade. Não certifica conformidade jurídica da rede.</p></section><section class="card"><h2>Suas preferências</h2><form class="form" id="preferences-form"><label class="check"><input name="marketing" type="checkbox" ${state.preferences.marketing ? 'checked' : ''}>Autorizar comunicações de campanhas.</label><label class="check"><input name="segmentation" type="checkbox" ${state.preferences.segmentation ? 'checked' : ''}>Autorizar sugestões com base no histórico de compras.</label><button class="button" type="submit">Salvar preferências</button></form><p class="hint">Recusar ou revogar não impede a compra. Não coletamos idade nem dados sensíveis nesta demonstração.</p><div class="actions">${button('Exportar dados da sessão', 'export', '', 'secondary')}${button('Excluir conta de teste', 'erase', state.user ? '' : 'disabled', 'danger')}</div><p class="hint">A exclusão remove o perfil e desvincula seu identificador dos pedidos fictícios. Totem: encerrar atendimento apaga toda a sessão.</p></section></div>`;
}
export function operationsView() {
  const orders = state.orders.filter(order => order.unit === state.unit);
  const paid = orders.filter(order => order.payment === 'aprovado');
  return `${head('Da cozinha ao balcão.', 'Painel demonstrativo da unidade selecionada. Os papéis são representados sem autenticação administrativa real.')}<div class="metrics"><div class="card metric">Pedidos pagos<strong>${paid.length}</strong></div><div class="card metric">Em preparo<strong>${paid.filter(order => order.stage === 1).length}</strong></div><div class="card metric">Prontos<strong>${paid.filter(order => order.stage === 2).length}</strong></div><div class="card metric">Vendas simuladas<strong>${money(paid.reduce((sum, order) => sum + order.total, 0))}</strong></div></div><section class="card"><h2>Cozinha e atendente</h2>${paid.length ? paid.map(order => `<div class="cart-line"><div><strong>${order.code} · ${orderStates[order.stage]}</strong><small>${order.items.map(item => `${item.quantity} × ${escape(item.name)}${item.extras.length ? ' + ' + item.extras.map(extra => escape(extra.name)).join(', ') : ''}${item.note ? ' / ' + escape(item.note) : ''}`).join('; ')}</small></div>${order.stage < 3 ? button(['Iniciar preparo', 'Marcar pronto', 'Confirmar retirada'][order.stage], 'advance', `data-id="${order.id}"`, 'secondary') : '<span class="status">Concluído</span>'}</div>`).join('') : '<p class="muted">Nenhum pedido com pagamento confirmado nesta unidade.</p>'}</section><section class="card" style="margin-top:1rem"><h2>Gerência · disponibilidade local</h2><div class="table-wrap"><table><caption class="sr-only">Estoque fictício por produto na unidade</caption><thead><tr><th>Produto</th><th>Saldo</th><th>Situação</th></tr></thead><tbody>${catalog().map(product => `<tr><td>${product.name}</td><td>${product.stock}</td><td>${available(product, state.unit) ? 'Disponível' : 'Indisponível'}</td></tr>`).join('')}</tbody></table></div><h3 style="margin-top:1.5rem">Registro das operações da sessão</h3>${state.audit.length ? `<ul class="privacy-list">${state.audit.map(event => `<li>${escape(event.order)} · ${escape(event.action)}</li>`).join('')}</ul>` : '<p class="hint">Os eventos aparecerão após confirmações e mudanças de status.</p>'}<p class="hint">Relatórios consolidados, ajustes de estoque, descontos excepcionais e controle de acesso são responsabilidades futuras do back-end.</p></section>`;
}
